[package]
name = "file_classification_cli"
version = "0.2.0"
edition = "2024"

[dependencies]
file_classification_common = { path = "../common" }
file_classification_core = { path = "../file_classification_core" }
clap = { version = "4.5", features = ["derive"] }
dialoguer = "0.12.0"
rustyline = "17.0.2"
shlex = "1.3.0"
chrono = { workspace = true }

[[bin]]
name = "file_classification_cli"
path = "src/main.rs"

[dev-dependencies]
assert_cmd = "2.0.14"

[target.'cfg(not(target_env = "musl"))'.dependencies]

[features]
default = ["sqlite-bundled"]
sqlite = ["file_classification_core/sqlite"]
mysql = ["file_classification_core/mysql"]
postgres = ["file_classification_core/postgres"]
sqlite-bundled = ["file_classification_core/sqlite-bundled"]
mysql-bundled = ["file_classification_core/mysql-bundled"]
postgres-bundled = ["file_classification_core/postgres-bundled"]
