[package]
name = "file_classification_cli"
version = "0.2.0"
edition = "2024"

[dependencies]
diesel = { workspace = true }
file_classification_core = { path = "../file_classification_core" }
chrono = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
dialoguer = "0.10.4"
rustyline = "14.0.0"
shlex = "1.3.0"
regex = "1.11.3"
rusqlite = "0.37.0"

[[bin]]
name = "file_classification_cli"
doc = false

[dev-dependencies]
assert_cmd = "2.0.14"
