[workspace]
resolver = "2"
members = ["file_classification_*"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[workspace.dependencies]
# NOTE: 可选数据库后端（todo）
#pq-sys = { version = "0.7", features = ["bundled"] }
#libsqlite3-sys = { version = "0.35", features = ["bundled"] }
#mysqlclient-sys = { version = "0.4", features = ["bundled"] }

#openssl-sys = { version = "0.9", features = ["vendored"] }
libsqlite3-sys = { version = "0.35", features = ["bundled"] }
diesel = { version = "2.2", features = [
    "sqlite",
#    "mysql",
#    "postgres",
    "chrono",
    "returning_clauses_for_sqlite_3_35",
    "r2d2",
] }
dotenvy = "0.15"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
utoipa = { version = "4" }
utoipa-swagger-ui = { version = "4"}