[package]
name = "file_classification_core"
version = "0.2.0"
edition = "2024"

[dependencies]
diesel = { workspace = true }
dotenvy = { workspace = true }
chrono = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
#mysqlclient-sys = { workspace = true }
#libsqlite3-sys = { workspace = true }
#openssl-sys = { workspace = true }
#pq-sys = { workspace = true }
