[package]
name = "file_classification_core"
version = "0.2.0"
edition = "2024"

[dependencies]
diesel = { workspace = true }
diesel_migrations = { workspace = true }
libsqlite3-sys = { version = "0.35", features = ["bundled"], optional = true }
mysqlclient-sys = { version = "0.4", features = ["bundled"], optional = true }
pq-sys = { version = "0.7", features = ["bundled"], optional = true }
openssl-sys = { version = "0.9", features = ["vendored"], optional = true }
chrono = { workspace = true }
serde = { workspace = true }
utoipa = { workspace = true, optional = true }

[features]
default = ["sqlite"]
sqlite = ["libsqlite3-sys", "diesel/sqlite", "diesel/returning_clauses_for_sqlite_3_35"]
mysql = ["mysqlclient-sys", "diesel/mysql"]
postgres = ["pq-sys", "openssl-sys", "diesel/postgres"]
swagger = ["utoipa"]